import Foundation

enum CropsA {
    static let list: [Crop] = [
        Crop("tomato", "Tomato", "Solanum lycopersicum", .nightshade, "Solanaceae",
             indoors: 6...8, out: 1...2, direct: nil, days: 65...85, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 45, fall: nil,
             with: ["basil", "carrot", "marigold"], against: ["potato", "fennel"],
             form: .fruitBush, tint: 0,
             note: "The crop the whole calendar is built around. Started under lights six to eight weeks before the last frost, hardened off for a week, and set out only when nights hold above fifty degrees, one to two weeks after the frost date. Plant it deep, up to the first true leaves, and the buried stem roots. Indeterminate kinds climb and crop until frost; bush kinds give one flush. Feed lightly, water deeply and evenly, and mulch once the soil is warm.",
             trouble: "Blossom-end rot is a black leathery patch on the fruit base, caused by uneven water rather than a lack of lime; mulch and a steady schedule cure it. Late blight arrives in a wet August as brown greasy blotches on leaf and stem, and a plant with it comes out the same day."),
        Crop("pea", "Pea", "Pisum sativum", .legume, "Fabaceae",
             indoors: nil, out: nil, direct: (-6)...(-4), days: 60...70, per: 8, inches: 3,
             hardy: .hardy, again: nil, window: 21, fall: 8...10,
             with: ["carrot", "radish", "cucumber"], against: ["onion", "garlic"],
             form: .vine, tint: 1,
             note: "The first seed in the ground. Peas are sown as soon as the soil can be worked, four to six weeks before the last frost, in a double row three inches apart with a trellis between. They germinate in cold soil that would rot a bean, fix their own nitrogen, and are finished by the time the heat comes, which leaves the bed for a summer crop. Pick every other day while the pods are still tender.",
             trouble: "Sown late, peas hit summer heat while flowering and the crop collapses to a handful of pods. Powdery mildew whitens the leaves in a dry June; pull the vines and sow again for autumn. Pigeons and mice take the seed before it sprouts, so cover the row until it is up."),
        Crop("carrot", "Carrot", "Daucus carota", .umbel, "Apiaceae",
             indoors: nil, out: nil, direct: (-3)...(-2), days: 70...80, per: 16, inches: 3,
             hardy: .halfHardy, again: 21, window: 30, fall: 10...12,
             with: ["tomato", "onion", "lettuce"], against: ["dill", "parsnip"],
             form: .root, tint: 2,
             note: "Direct-sown two to three weeks before the last frost into fine, stone-free soil, and again every three weeks until midsummer for a steady pull. The seed is tiny and slow, taking up to three weeks to show, so the row is marked with radish that comes up in five days. Thin to three inches when the tops are a finger high. Carrots left in the ground through the first frosts turn sweet.",
             trouble: "Carrot fly lays eggs at the crown when it smells a thinned row, and the maggots tunnel the root; thin in the evening, firm the soil back, and cover with fine mesh. Forked roots come from stones or fresh manure. A green shoulder is sun on the crown; earth it up."),
        Crop("garlic", "Garlic", "Allium sativum", .allium, "Amaryllidaceae",
             indoors: nil, out: nil, direct: nil, days: 240...270, per: 4, inches: 6,
             hardy: .hardy, again: nil, window: 21, fall: 4...8,
             with: ["tomato", "carrot", "strawberry"], against: ["pea", "bushbean"],
             form: .bulb, tint: 3,
             note: "The one crop that goes in as the season ends. Cloves are set pointed end up, two inches deep and six apart, four to eight weeks before the first fall frost, so they root before winter and are up with the snowdrops. Hardneck kinds throw a curling scape in June that is cut and eaten; the bulb is lifted in July when the lower leaves have browned, then cured in an airy shade for three weeks.",
             trouble: "Planted too early it makes soft top growth that winter burns; too late and the root is too small to hold through frost heave. Rust spots the leaves in a wet spring but rarely costs the bulb. Lifted late, the wrapper skins split and the bulb will not store."),
        Crop("lettuce", "Lettuce", "Lactuca sativa", .aster, "Asteraceae",
             indoors: 4...6, out: (-2)...0, direct: (-2)...0, days: 45...55, per: 4, inches: 6,
             hardy: .halfHardy, again: 14, window: 14, fall: 6...8,
             with: ["carrot", "radish", "strawberry"], against: ["parsley", "celery"],
             form: .head, tint: 4,
             note: "The succession crop that teaches succession. A short row sown every fortnight from two weeks before the last frost gives a cutting every week, and the same row sown all at once gives a glut and a compost heap. Loose-leaf kinds are cut from the outside and keep giving; heading kinds are pulled whole. In the heat of July lettuce is sown in the shade of a taller crop and watered every day.",
             trouble: "Bolting: the plant runs up to a bitter tower of flower the moment days are long and nights are warm, and it cannot be stopped once it starts. Sow heat-tolerant kinds in summer and give shade. Slugs shred the seedlings; tip burn on the inner leaves is water stress."),
        Crop("kale", "Kale", "Brassica oleracea", .brassica, "Brassicaceae",
             indoors: 6...8, out: (-4)...(-2), direct: (-4)...(-2), days: 55...75, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 60, fall: 6...8,
             with: ["beet", "onion", "potato"], against: ["tomato", "strawberry"],
             form: .leafy, tint: 5,
             note: "The hardiest leaf in the plot, started indoors in late winter and set out a month before the last frost, or sown direct in place. It is picked from the bottom up, a few leaves at a time, and a single plant will give from June until deep winter. The best sowing is the summer one for autumn: kale that has been through a frost is sweeter than any spring leaf, and it stands under snow.",
             trouble: "Cabbage whites lay on the underside of the leaves and the caterpillars strip a plant in days; net it or pick them off. Aphids cluster grey on the growing tips in a dry spell. Clubroot swells and rots the root in acid soil, so lime the bed and keep the brassicas moving."),
        Crop("cabbage", "Cabbage", "Brassica oleracea", .brassica, "Brassicaceae",
             indoors: 6...8, out: (-4)...(-2), direct: nil, days: 70...100, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 21, fall: 10...12,
             with: ["onion", "potato", "dill"], against: ["tomato", "strawberry"],
             form: .head, tint: 6,
             note: "Cabbage is the family's terminal bud grown large. It is started under cover six to eight weeks before the last frost, set out a month before it, and firmed in hard, because a loose cabbage makes a loose head. It wants rich soil, lime, and steady water; a dry spell followed by rain splits the heads. Early kinds are cut small in June, storage kinds are left until after the first frosts and will keep for months.",
             trouble: "Split heads follow a rainstorm after drought; twist the plant a quarter turn to break some roots and slow the intake. Cabbage root fly maggots wilt a transplant in its first month, so a collar of card at the stem stops the egg-laying. Cabbage whites and clubroot as for kale."),
        Crop("broccoli", "Broccoli", "Brassica oleracea", .brassica, "Brassicaceae",
             indoors: 6...8, out: (-3)...(-2), direct: nil, days: 60...80, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 14, fall: 10...12,
             with: ["onion", "beet", "dill"], against: ["tomato", "strawberry"],
             form: .head, tint: 7,
             note: "Broccoli is the flower of the cabbage family cut while the buds are tight. Started indoors and set out two to three weeks before the last frost, it makes one central head in about two months and then, if the stem is left, a run of side shoots for another month. It is a cool-season crop that the summer ruins; the fall planting, set out in late summer to head in cool October, is the reliable one.",
             trouble: "A head that flowers yellow before it is cut has bolted in the heat and is past eating; cut a day early rather than a day late. Buttoning, where a small plant makes a tiny head and stops, follows a cold check at transplanting. Cabbage whites take the leaves."),
        Crop("cauliflower", "Cauliflower", "Brassica oleracea", .brassica, "Brassicaceae",
             indoors: 6...8, out: (-2)...(-1), direct: nil, days: 60...80, per: 1, inches: 12,
             hardy: .halfHardy, again: nil, window: 10, fall: 10...12,
             with: ["onion", "celery", "beet"], against: ["tomato", "strawberry"],
             form: .head, tint: 8,
             note: "The fussiest of the family. Cauliflower must never be checked: a cold night, a dry week or a cramped pot at transplanting and it makes a button and stops. It is set out a week or two before the last frost into the richest soil in the plot, watered without fail, and the curd is shaded by folding a leaf over it when it shows, which keeps it white. The window for cutting is short; a week too long and the curd opens and goes ricey.",
             trouble: "Buttoning and blindness, a plant with no head at all, both trace back to a check in the seedling weeks. A loose, ricey or purple-tinged curd is sun and heat on an unshaded head. Boron shortage browns the curd from within; a little compost usually carries enough."),
        Crop("kohlrabi", "Kohlrabi", "Brassica oleracea", .brassica, "Brassicaceae",
             indoors: 4...6, out: (-3)...(-1), direct: (-3)...(-1), days: 45...60, per: 4, inches: 6,
             hardy: .hardy, again: 21, window: 14, fall: 6...8,
             with: ["beet", "onion", "cucumber"], against: ["tomato", "polebean"],
             form: .bulb, tint: 9,
             note: "A cabbage that swells its stem into a sweet turnip-flavoured globe sitting on the soil. It is quick, six to eight weeks, and sown in small batches every three weeks from a month before the last frost. Pull it at tennis-ball size; larger and it goes woody. Purple kinds stand the heat a little better. Because it is shallow-rooted it is one of the few brassicas that transplants without complaint.",
             trouble: "Left too long, the globe turns to wood and the flavour goes hot. Split stems follow uneven water. As with every brassica, flea beetles pepper the seedlings with pinholes in a dry spring and cabbage whites arrive in June; a fine mesh over the row solves both.")
    ]
}

enum CropsB {
    static let list: [Crop] = [
        Crop("radish", "Radish", "Raphanus sativus", .brassica, "Brassicaceae",
             indoors: nil, out: nil, direct: (-4)...(-2), days: 22...30, per: 16, inches: 3,
             hardy: .hardy, again: 10, window: 7, fall: 4...6,
             with: ["pea", "lettuce", "carrot"], against: ["potato", "cabbage"],
             form: .root, tint: 10,
             note: "The fastest thing in the plot: sown four weeks before the last frost, up in five days, pulled in twenty-five. It is the crop that marks slow rows, that fills the gaps between transplants, and that is sown ten days apart all spring so there is always a bunch ready. It stops in summer heat and starts again in September. Pull it the week it is ready; it does not wait.",
             trouble: "A radish left a week too long goes hollow and hot, and in heat it bolts to flower without swelling at all. Flea beetles pit the leaves. Sown too thick and not thinned, it makes tops and no roots; give each seed three inches."),
        Crop("beet", "Beet", "Beta vulgaris", .amaranth, "Amaranthaceae",
             indoors: nil, out: nil, direct: (-4)...(-2), days: 50...65, per: 9, inches: 4,
             hardy: .halfHardy, again: 21, window: 21, fall: 8...10,
             with: ["onion", "kohlrabi", "lettuce"], against: ["polebean", "fennel"],
             form: .root, tint: 11,
             note: "Beet seed is a corky cluster holding several seeds, so every sowing comes up as a clump and must be thinned; the thinnings are a salad. Sown direct from a month before the last frost and again every three weeks, it gives roots in two months and edible greens from the start. Golf-ball beets are the sweetest. The fall sowing, lifted before hard frost, stores in sand through winter.",
             trouble: "Unthinned clusters give a tangle of pencil roots. Woody, ringed roots come from drought followed by rain. A scab of corky patches means the soil is too alkaline or too dry. Leaf miner tunnels the leaves grey in early summer; pick and bin the affected leaves."),
        Crop("chard", "Chard", "Beta vulgaris", .amaranth, "Amaranthaceae",
             indoors: nil, out: nil, direct: (-2)...0, days: 50...60, per: 4, inches: 6,
             hardy: .halfHardy, again: nil, window: 90, fall: 8...10,
             with: ["onion", "kohlrabi", "bushbean"], against: ["polebean", "cucumber"],
             form: .leafy, tint: 12,
             note: "Chard is a beet grown for the leaf, and the most forgiving green in the plot. One sowing around the last frost is cut from the outside for the whole season and often through a mild winter; it does not bolt in summer the way spinach does. The ribs come white, gold and crimson and are cooked as a separate vegetable. Four plants to a square give a household all it can eat.",
             trouble: "Slugs take the seedlings and hide in the crinkled leaves. Leaf spot appears as brown rings in a wet summer and is only cosmetic. A plant that overwinters bolts in its second spring; pull it and sow again. Otherwise chard has very little that goes wrong."),
        Crop("spinach", "Spinach", "Spinacia oleracea", .amaranth, "Amaranthaceae",
             indoors: nil, out: nil, direct: (-6)...(-4), days: 40...50, per: 9, inches: 4,
             hardy: .hardy, again: 14, window: 14, fall: 6...8,
             with: ["strawberry", "pea", "radish"], against: ["potato", "fennel"],
             form: .leafy, tint: 13,
             note: "The earliest green, sown with the peas six weeks before the last frost, and one of the first to finish. It germinates in cold soil, grows fast in cool weather and bolts the moment the days pass thirteen hours, so the spring crop is a short one sown every two weeks. The autumn sowing is the better one: it grows into the cold, is sweet after frost, and under a cloche will give leaves through winter.",
             trouble: "Bolting is the whole story: heat and long days send it to seed in a week. Sow early, sow again in late summer, and choose slow-bolting kinds. Downy mildew yellows the leaves in a damp spring. Leaf miner leaves grey tunnels; remove the leaves before the maggots drop."),
        Crop("onion", "Onion", "Allium cepa", .allium, "Amaryllidaceae",
             indoors: 8...10, out: (-4)...(-2), direct: (-4)...(-2), days: 90...120, per: 9, inches: 4,
             hardy: .hardy, again: nil, window: 21, fall: nil,
             with: ["carrot", "beet", "lettuce"], against: ["pea", "bushbean"],
             form: .bulb, tint: 14,
             note: "Bulb onions are grown from sets, small bulbs planted a month before the last frost with the tip just showing, or from seed started under lights ten weeks earlier. They bulb up when the day length reaches the trigger for their kind, so a late planting makes a small bulb no matter how long it grows. The tops fall over in August; lift, dry in the sun for a fortnight, and string them.",
             trouble: "Bolting: a set planted too large, or checked by cold, throws a flower stalk and the bulb will not store. Onion fly maggots hollow a young bulb. White rot, a fluffy fungus at the base, persists in the soil for years and is the reason the alliums move every season."),
        Crop("leek", "Leek", "Allium ampeloprasum", .allium, "Amaryllidaceae",
             indoors: 8...10, out: (-2)...0, direct: nil, days: 100...130, per: 9, inches: 4,
             hardy: .hardy, again: nil, window: 90, fall: nil,
             with: ["carrot", "celery", "onion"], against: ["pea", "bushbean"],
             form: .stalk, tint: 15,
             note: "The winter allium. Leeks are started under cover in late winter, grown to pencil thickness, and dropped into six-inch holes made with a dibber around the last frost, watered in and left; the hole fills by itself and blanches the shank. They stand in the bed through frost and snow and are lifted as wanted from October to March. Earthing up in autumn lengthens the white part.",
             trouble: "Leek moth and allium leaf miner tunnel the shank and let rot in; a mesh cover from May stops both. Rust orange-spots the leaves in a wet season but the shank is unharmed. A leek that bolts in its second spring has a hard core and is only fit for stock."),
        Crop("scallion", "Scallion", "Allium fistulosum", .allium, "Amaryllidaceae",
             indoors: 6...8, out: (-2)...0, direct: (-4)...(-2), days: 60...70, per: 16, inches: 3,
             hardy: .hardy, again: 21, window: 30, fall: 6...8,
             with: ["carrot", "lettuce", "tomato"], against: ["pea", "bushbean"],
             form: .stalk, tint: 16,
             note: "Bunching onions never bulb; they are sown thickly in a band from a month before the last frost and pulled at pencil size from about nine weeks. Sown every three weeks they carry through the season, and a late-summer sowing overwinters for the first pull of spring. They take almost no room, sixteen to a square, and tuck into the ends of beds and the edges of paths.",
             trouble: "Little goes wrong. Onion fly can hollow the base in a dry May. Sown too thinly they grow thick and coarse; sown too thickly they stay thin and can be pulled as chives. Weeds outrun them easily because the leaves throw no shade, so the band is hand-weeded."),
        Crop("potato", "Potato", "Solanum tuberosum", .nightshade, "Solanaceae",
             indoors: nil, out: nil, direct: (-4)...(-2), days: 80...110, per: 1, inches: 12,
             hardy: .halfHardy, again: nil, window: 30, fall: nil,
             with: ["bushbean", "corn", "cabbage"], against: ["tomato", "cucumber"],
             form: .tuber, tint: 17,
             note: "Seed potatoes are chitted on a windowsill until they have short green sprouts, then planted a hand deep a month before the last frost. As the shoots rise they are earthed up twice, which buries the stem where the new tubers form and keeps them from the light that turns them green. Earlies are lifted when they flower; maincrop when the tops die back, then dried a few hours before storing in the dark.",
             trouble: "Late blight, the same fungus as on tomatoes, arrives in warm wet weather as dark blotches and can rot a crop in the ground; cut the tops at the first sign and lift two weeks later. Scab is cosmetic. Green tubers are poisonous; earth up. Never plant where tomatoes stood last year."),
        Crop("pepper", "Pepper", "Capsicum annuum", .nightshade, "Solanaceae",
             indoors: 8...10, out: 2...3, direct: nil, days: 65...90, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 60, fall: nil,
             with: ["basil", "tomato", "carrot"], against: ["fennel", "kohlrabi"],
             form: .fruitBush, tint: 18,
             note: "Peppers want more of everything than tomatoes: earlier sowing, warmer soil, longer summer. They are started under lights eight to ten weeks before the last frost and not set out until two or three weeks after it, when nights are reliably warm. A plant checked by a cold night sulks for a month. They fruit from midsummer until frost, green first and then, if left, red, yellow or orange and far sweeter.",
             trouble: "Blossom drop in a cold or very hot spell; nothing to do but wait. Sunscald is a papery white patch on fruit that has lost its leaf shade. Blossom-end rot as on tomato. Aphids on the tips. A plant that grows leaves and no fruit has been fed too much nitrogen."),
        Crop("eggplant", "Eggplant", "Solanum melongena", .nightshade, "Solanaceae",
             indoors: 8...10, out: 2...3, direct: nil, days: 65...85, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 45, fall: nil,
             with: ["bushbean", "pepper", "marigold"], against: ["fennel", "corn"],
             form: .fruitBush, tint: 19,
             note: "The most heat-loving of the nightshades. Eggplant is sown under lights ten weeks before the last frost, potted on twice, and set out three weeks after it into the warmest spot in the plot, ideally through black plastic. It needs staking; the fruit is heavy. Cut, never pull, when the skin is glossy and springs back from a thumb; a dull skin means overripe and bitter seeds.",
             trouble: "Flea beetles riddle the leaves with holes and can kill a small plant; cover until it is established. Verticillium wilt yellows one side of the plant and is in the soil, so rotate. Cold nights at planting stop growth for weeks. Spider mites in a hot dry August.")
    ]
}
