import Foundation

enum CropsC {
    static let list: [Crop] = [
        Crop("tomatillo", "Tomatillo", "Physalis philadelphica", .nightshade, "Solanaceae",
             indoors: 6...8, out: 1...2, direct: nil, days: 70...85, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 45, fall: nil,
             with: ["basil", "marigold", "carrot"], against: ["potato", "fennel"],
             form: .fruitBush, tint: 20,
             note: "A sprawling cousin of the tomato that grows a green fruit inside a papery lantern. It is started and set out on the tomato calendar, six to eight weeks under lights and out a week or two after the last frost, but it needs two plants to set fruit, since one will not pollinate itself. It is tougher than tomato in drought and in poor soil. The fruit is ready when it fills the husk and the husk begins to split.",
             trouble: "A single plant flowers all summer and sets nothing; always grow a pair. The plants flop and the fruit rots on wet ground, so cage them. Fruit picked before it fills the husk is sour and hard. The same beetles and blight as tomato, though it shrugs them off better."),
        Crop("cucumber", "Cucumber", "Cucumis sativus", .cucurbit, "Cucurbitaceae",
             indoors: 3...4, out: 1...2, direct: 1...3, days: 50...65, per: 2, inches: 6,
             hardy: .veryTender, again: 21, window: 30, fall: nil,
             with: ["pea", "radish", "sunflower"], against: ["potato", "sage"],
             form: .vine, tint: 21,
             note: "Cucumbers are sown direct a week or two after the last frost when the soil is warm to the hand, or started three weeks earlier in pots they can be tipped out of whole, because the roots hate disturbance. Two plants to a square on a trellis gives straight fruit and dry leaves. A second sowing three weeks later keeps the picking going into September. Pick daily; one missed fruit swelling to a marrow stops the vine.",
             trouble: "Bitter fruit comes from drought and heat stress; water deeply and often. Powdery mildew coats the leaves white in late summer and shortens the season. Cucumber beetles carry bacterial wilt, which collapses a vine in days. Fruit that yellows small and drops was not pollinated."),
        Crop("zucchini", "Zucchini", "Cucurbita pepo", .cucurbit, "Cucurbitaceae",
             indoors: 3...4, out: 1...2, direct: 1...3, days: 45...60, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 45, fall: nil,
             with: ["corn", "bushbean", "nasturtium"], against: ["potato", "pumpkin"],
             form: .bush, tint: 22,
             note: "One plant feeds a family; two feed the street. Zucchini is sown direct a week or two after the last frost, three seeds to a station thinned to one, or started in a pot three weeks ahead. It wants a whole square and will lean into the next one. Cut the fruit at six inches with a knife, every day in August, because a fruit left to swell tells the plant to stop. The first flowers are male and fall off; that is normal.",
             trouble: "Fruit that rots from the tip while small was not pollinated, common in a cold wet week; hand-pollinate with a male flower. Powdery mildew in late summer. Squash vine borer tunnels the stem at the base and the plant wilts in a day; slit the stem and remove the grub."),
        Crop("wintersquash", "Winter Squash", "Cucurbita maxima", .cucurbit, "Cucurbitaceae",
             indoors: 3...4, out: 1...2, direct: 1...2, days: 85...110, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 21, fall: nil,
             with: ["corn", "bushbean", "nasturtium"], against: ["potato", "cucumber"],
             form: .vine, tint: 23,
             note: "Butternut, acorn, hubbard and their kin are sown direct as soon as the soil is warm after the last frost, or started three weeks earlier in pots, and given the long season they need to ripen a hard shell. The vines run ten feet; they are sent along a path or up a strong trellis with the fruit in slings. Harvest before the first frost when the stem has corked and a thumbnail will not mark the skin, then cure in the sun for ten days.",
             trouble: "Picked soft, before the skin hardens, it will not keep past November. A frost on the fruit ruins it in store. Powdery mildew strips the leaves in September and stops the ripening; keep the plant watered at the root. Vine borer and squash bugs as for zucchini."),
        Crop("pumpkin", "Pumpkin", "Cucurbita pepo", .cucurbit, "Cucurbitaceae",
             indoors: 3...4, out: 1...2, direct: 1...2, days: 90...120, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 21, fall: nil,
             with: ["corn", "bushbean", "marigold"], against: ["potato", "zucchini"],
             form: .vine, tint: 24,
             note: "Pumpkins take a hundred days and a great deal of room, so they are sown at the plot's edge just after the last frost and pointed away from everything else. Two or three fruits to a vine is enough; pinch the rest and the ones that are left grow large. A board under each fruit keeps it off wet soil. Cut with a length of stem when the skin is fully coloured and hard, and cure in the sun before the first frost.",
             trouble: "A pumpkin that sets in a wet week rots at the blossom end while small. Powdery mildew in late summer. Squash bugs cluster under the leaves and suck them grey. Vine borer at the base. A late sowing will not colour before frost; the days to maturity are not negotiable."),
        Crop("melon", "Melon", "Cucumis melo", .cucurbit, "Cucurbitaceae",
             indoors: 3...4, out: 2...3, direct: 2...3, days: 75...90, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 21, fall: nil,
             with: ["corn", "nasturtium", "radish"], against: ["potato", "cucumber"],
             form: .vine, tint: 25,
             note: "Cantaloupe and honeydew need warm soil and a warm summer, and in a short-season plot they are started in pots three weeks before the last frost and set out two or three weeks after it through black plastic. The vines want sun on every leaf and a dry week before harvest to concentrate the sugar. A cantaloupe is ripe when the netting is raised and the fruit slips from the stem with a thumb.",
             trouble: "Cold soil at sowing rots the seed. Bland, watery fruit comes from rain in the last two weeks; withhold water as the fruit ripens. Powdery mildew and cucumber beetles as for cucumber. Fruit that splits was watered heavily after a drought."),
        Crop("watermelon", "Watermelon", "Citrullus lanatus", .cucurbit, "Cucurbitaceae",
             indoors: 3...4, out: 2...3, direct: 2...3, days: 75...95, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 21, fall: nil,
             with: ["corn", "nasturtium", "radish"], against: ["potato", "cucumber"],
             form: .vine, tint: 26,
             note: "The most demanding cucurbit for heat and space. Small-fruited kinds are the ones for a square-foot plot: started in pots three weeks before the last frost, set out two or three weeks after it on black plastic, and trellised with the fruit in slings. Ripeness is read from the tendril nearest the fruit, which browns and dries, and from the ground spot, which turns from white to cream yellow.",
             trouble: "Picked early there is no way back; a watermelon does not ripen off the vine. Cold nights at planting stunt the vine for the season. Anthracnose spots the leaves and fruit in wet weather. Cucumber beetles and powdery mildew as for the rest of the family."),
        Crop("bushbean", "Bush Bean", "Phaseolus vulgaris", .legume, "Fabaceae",
             indoors: nil, out: nil, direct: 1...3, days: 50...60, per: 9, inches: 4,
             hardy: .tender, again: 14, window: 21, fall: 8...10,
             with: ["carrot", "cucumber", "corn"], against: ["onion", "garlic"],
             form: .bush, tint: 27,
             note: "Beans rot in cold soil, so they wait until a week or two after the last frost and go in an inch deep, nine to a square. A bush bean crops for three weeks and is done, which is why a short row is sown every two weeks until midsummer. Pick every second day while the pods snap; let them go and the plant stops. They fix their own nitrogen and leave the bed richer than they found it.",
             trouble: "Seed sown into cold wet soil rots before it sprouts; wait for warmth. Bean beetles skeletonise the leaves in July. Rust and anthracnose spot the pods in a wet season; never handle the plants when the leaves are wet. Slugs take the seedlings the night they emerge."),
        Crop("polebean", "Pole Bean", "Phaseolus vulgaris", .legume, "Fabaceae",
             indoors: nil, out: nil, direct: 1...3, days: 60...70, per: 8, inches: 3,
             hardy: .tender, again: nil, window: 45, fall: nil,
             with: ["corn", "radish", "cucumber"], against: ["onion", "beet"],
             form: .vine, tint: 28,
             note: "Pole beans take a fortnight longer than bush beans to start but crop for two months instead of three weeks, and they do it standing up, on a tepee or a trellis, eight plants to a square. They go in a week or two after the last frost when the soil is warm. Once the vines top the pole, pinch the tips. The old three-sisters planting runs them up a corn stalk with squash below.",
             trouble: "Vines that reach the top of a pole with no flowers are being fed too much nitrogen. Cold soil rots the seed. Bean beetles and rust as for bush beans. Beans left on the vine to swell stop the plant setting more; pick young and often."),
        Crop("fava", "Fava Bean", "Vicia faba", .legume, "Fabaceae",
             indoors: nil, out: nil, direct: (-8)...(-6), days: 75...90, per: 4, inches: 6,
             hardy: .hardy, again: nil, window: 21, fall: nil,
             with: ["potato", "corn", "cucumber"], against: ["onion", "garlic"],
             form: .tall, tint: 29,
             note: "The bean that goes in with the peas, or before them: six to eight weeks ahead of the last frost, two inches deep, four to a square. It is a cool-weather crop that stands frost and stops setting in heat, so the early sowing matters. The plants are tall and are staked with string around the block. Pinch out the tops when the first pods set; that stops the blackfly and the tops are eaten.",
             trouble: "Black bean aphid colonises the growing tips in May; pinching the tops removes their landing ground. Chocolate spot browns the leaves in a damp season. Sown late, the flowers drop in the first hot week and the pods never come. Rust late in the season is harmless.")
    ]
}

enum CropsD {
    static let list: [Crop] = [
        Crop("corn", "Sweet Corn", "Zea mays", .grass, "Poaceae",
             indoors: nil, out: nil, direct: 1...3, days: 65...90, per: 4, inches: 6,
             hardy: .tender, again: 14, window: 10, fall: nil,
             with: ["bushbean", "wintersquash", "cucumber"], against: ["tomato", "celery"],
             form: .tall, tint: 30,
             note: "Corn is wind-pollinated, so it is planted in a block of at least four squares, never a single row, and the pollen from the tassels falls onto the silks below. It goes in a week or two after the last frost when the soil is warm, four to a square, and is fed hard; it is the hungriest crop in the plot. Each stalk gives one or two ears. They are ready when the silks brown and a kernel pressed with a thumbnail spurts milk.",
             trouble: "Ears with gaps in the kernels were badly pollinated, the usual fault of a single row. Corn earworm eats down from the tip; cut it off. Raccoons and birds know the day before you do. Smut is a grey swollen gall on the ear; cut it out. Lodging follows a storm on a shallow-rooted, unhilled stand."),
        Crop("okra", "Okra", "Abelmoschus esculentus", .sundry, "Malvaceae",
             indoors: 3...4, out: 2...4, direct: 2...4, days: 55...65, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 45, fall: nil,
             with: ["pepper", "eggplant", "basil"], against: ["fennel", "potato"],
             form: .tall, tint: 31,
             note: "A mallow, cousin to hibiscus and cotton, with the same yellow flower. Okra wants heat above everything: it is sown direct two to four weeks after the last frost when the soil is truly warm, or started in pots three weeks earlier, and it does nothing until July and then grows a foot a week. The pods are cut at three inches, every other day, with gloves against the prickles. Left a day too long they are wood.",
             trouble: "Sown into cool soil the seed rots or the seedling sulks all season. Pods harden fast; pick small and often. Aphids and stink bugs on the pods. In a cool summer the plant flowers late and gives little; it is a crop for a hot site."),
        Crop("sweetpotato", "Sweet Potato", "Ipomoea batatas", .sundry, "Convolvulaceae",
             indoors: 10...12, out: 2...4, direct: nil, days: 90...120, per: 1, inches: 12,
             hardy: .veryTender, again: nil, window: 14, fall: nil,
             with: ["bushbean", "okra", "basil"], against: ["wintersquash", "potato"],
             form: .runner, tint: 32,
             note: "Not a potato at all but a morning glory grown from slips, rooted shoots sprouted from a tuber in warm water ten to twelve weeks before the last frost. The slips are set out two to four weeks after it into warm soil, one to a square, and the vines run over everything for a hundred days. Dig before the first frost, on a dry day, and cure the roots in warmth for ten days to sweeten them.",
             trouble: "Slips set into cold soil rot at the base. Vines that root along their length make many small tubers; lift them off the ground now and then. A frost on the foliage spoils the roots below within a day. Wireworm and voles tunnel the tubers in a long-standing bed."),
        Crop("celery", "Celery", "Apium graveolens", .umbel, "Apiaceae",
             indoors: 10...12, out: 0...2, direct: nil, days: 85...120, per: 4, inches: 6,
             hardy: .halfHardy, again: nil, window: 45, fall: nil,
             with: ["onion", "cabbage", "leek"], against: ["carrot", "parsnip"],
             form: .stalk, tint: 33,
             note: "The longest indoor start in the plot: celery is sown on the surface under lights ten to twelve weeks before the last frost, since the seed needs light and takes three weeks to show. It is set out around the frost date into the wettest, richest ground available and never allowed to dry. Self-blanching kinds are planted in a block so they shade each other. Cut the outer stalks as needed from midsummer.",
             trouble: "A dry week gives hollow, stringy, bitter stalks and there is no recovery. A cold spell after planting makes it bolt. Celery leaf spot, brown flecks that spread in wet weather, comes on the seed. Slugs hide in the crown. Carrot fly, as for the rest of the family."),
        Crop("parsnip", "Parsnip", "Pastinaca sativa", .umbel, "Apiaceae",
             indoors: nil, out: nil, direct: (-3)...(-1), days: 100...120, per: 9, inches: 4,
             hardy: .hardy, again: nil, window: 60, fall: nil,
             with: ["onion", "garlic", "radish"], against: ["carrot", "celery"],
             form: .root, tint: 34,
             note: "Sown once, early, and forgotten. Parsnip seed is fresh every year, since it dies within months, and is sown direct a few weeks before the last frost into deep stone-free soil, three seeds to a station, thinned to one. It takes a month to come up and the whole season to grow, and it is left in the ground until the first hard frosts, which turn its starch to sugar. Dig as needed through winter.",
             trouble: "Old seed does not germinate at all; buy it fresh. Canker, an orange-brown rot at the shoulder, follows damage from carrot fly or from a hoe. Forked roots come from stones and manure. Sap on wet skin in sun causes burns; harvest in gloves and long sleeves."),
        Crop("turnip", "Turnip", "Brassica rapa", .brassica, "Brassicaceae",
             indoors: nil, out: nil, direct: (-4)...(-2), days: 40...60, per: 9, inches: 4,
             hardy: .hardy, again: 21, window: 14, fall: 8...10,
             with: ["pea", "onion", "spinach"], against: ["tomato", "polebean"],
             form: .root, tint: 35,
             note: "A quick brassica root sown direct from a month before the last frost, nine to a square, and pulled at golf-ball size in six to eight weeks. The spring sowing is a short one before the heat; the late-summer sowing for autumn is the sweeter crop and the tops make a second vegetable. Sow every three weeks in cool weather. Thin early; a crowded turnip makes leaf and no root.",
             trouble: "Woody, hot and hollow when left too long or grown in heat. Flea beetles pit the young leaves. Cabbage root fly maggots tunnel the root in May. Clubroot as for every brassica; keep the family moving and lime the bed."),
        Crop("rutabaga", "Rutabaga", "Brassica napus", .brassica, "Brassicaceae",
             indoors: nil, out: nil, direct: (-2)...0, days: 90...100, per: 4, inches: 6,
             hardy: .hardy, again: nil, window: 45, fall: 12...14,
             with: ["pea", "onion", "beet"], against: ["tomato", "polebean"],
             form: .root, tint: 36,
             note: "The swede, a cross of turnip and cabbage, grown for a storage root that wants a long cool season. In most zones it is sown direct in early summer, twelve to fourteen weeks before the first fall frost, so that it swells in the cool of autumn and is lifted after the first frosts have sweetened it. Four to a square, thinned early. It stores in sand or a cool shed until March.",
             trouble: "Sown in spring in a warm zone it bolts or goes woody in the summer heat. Brown heart, a hollow brown core, is boron shortage in dry alkaline soil. Cabbage root fly and flea beetle on the seedlings. Clubroot as for the family."),
        Crop("arugula", "Arugula", "Eruca vesicaria", .brassica, "Brassicaceae",
             indoors: nil, out: nil, direct: (-4)...(-2), days: 30...40, per: 16, inches: 3,
             hardy: .hardy, again: 14, window: 14, fall: 4...6,
             with: ["lettuce", "carrot", "cucumber"], against: ["strawberry", "tomato"],
             form: .leafy, tint: 37,
             note: "Rocket, the peppery salad leaf, sown thickly and cut at four inches, five weeks from sowing. It is sown from a month before the last frost every two weeks until the heat, then again from late summer into autumn; it stands light frost and is at its best after one. Sixteen to a square. Cut with scissors an inch above the crown and it grows back for a second and third cutting.",
             trouble: "It bolts within days of the first hot spell and the leaves go hot and tough; sow small and often, in summer in shade. Flea beetles shot-hole every leaf in a dry spring; mesh over the row stops them. Otherwise nothing goes wrong that a fresh sowing does not fix."),
        Crop("mizuna", "Mizuna", "Brassica rapa", .brassica, "Brassicaceae",
             indoors: nil, out: nil, direct: (-4)...(-2), days: 35...45, per: 9, inches: 4,
             hardy: .hardy, again: 14, window: 21, fall: 4...6,
             with: ["lettuce", "radish", "spinach"], against: ["tomato", "strawberry"],
             form: .leafy, tint: 38,
             note: "A Japanese mustard with finely cut feathery leaves and a mild flavour, one of the most cold-tolerant salads there is. Sown direct from a month before the last frost and again in late summer, nine to a square, and cut as a whole rosette or leaf by leaf. It grows back after cutting three or four times. Under a cloche it gives through most winters.",
             trouble: "Slower to bolt than arugula but it goes in the end, in July; the flowers are edible. Flea beetles in a dry spring. Slugs in a wet one. Crowded plants rot at the centre; give them their four inches."),
        Crop("bokchoy", "Bok Choy", "Brassica rapa", .brassica, "Brassicaceae",
             indoors: 4...5, out: (-2)...0, direct: (-3)...(-1), days: 40...50, per: 4, inches: 6,
             hardy: .halfHardy, again: 14, window: 14, fall: 6...8,
             with: ["onion", "carrot", "dill"], against: ["tomato", "strawberry"],
             form: .head, tint: 39,
             note: "A fast, spoon-leaved cabbage that makes a loose upright head in six to seven weeks. It is sown direct a few weeks before the last frost, or transplanted, four to a square, and cut whole at the base. Baby kinds are ready in a month. It is at its best in the cool of spring and autumn, and the late-summer sowing gives the cleanest heads with the fewest pests.",
             trouble: "A cold snap on a young plant makes it bolt before it heads; cover it or sow later. Flea beetles and cabbage whites as for every brassica. Slugs live in the base of the head. In summer heat it goes straight to flower.")
    ]
}
