import Foundation

enum CropsE {
    static let list: [Crop] = [
        Crop("endive", "Endive", "Cichorium endivia", .aster, "Asteraceae",
             indoors: 4...6, out: 0...1, direct: (-2)...0, days: 80...90, per: 4, inches: 6,
             hardy: .halfHardy, again: nil, window: 21, fall: 8...10,
             with: ["radish", "turnip", "onion"], against: ["celery", "fennel"],
             form: .head, tint: 40,
             note: "The bitter cousin of lettuce, frisée and escarole both, grown mainly as an autumn crop because it is at its best in the cool and sweetest after a frost. Sown direct around the last frost or, better, in midsummer for October, four to a square. The heads are blanched for a week before cutting by tying the outer leaves up or setting a plate over the centre, which turns the heart pale and mild.",
             trouble: "Blanched too long, the heart rots from the centre in damp weather; a week is enough. Summer-grown heads bolt and turn unbearably bitter. Slugs shelter in the loose heads. Tip burn in dry heat as for lettuce."),
        Crop("fennel", "Fennel", "Foeniculum vulgare", .umbel, "Apiaceae",
             indoors: nil, out: nil, direct: 0...2, days: 80...90, per: 4, inches: 6,
             hardy: .halfHardy, again: nil, window: 21, fall: 10...12,
             with: ["mint", "sage", "dill"], against: ["tomato", "bushbean"],
             form: .bulb, tint: 41,
             note: "Florence fennel, grown for the swollen aniseed bulb at the base of the stems. It is sown direct after the last frost, four to a square, and earthed up as the bulb forms to keep it white and tender. It is the one crop the plan keeps at arm's length: fennel roots give off a chemical that checks the growth of most neighbours, so it goes at the end of a bed or in a corner of its own. Cut at tennis-ball size.",
             trouble: "Bolting: a cold check, a dry spell or a spring sowing that runs into long days sends it straight to flower with no bulb; the midsummer sowing for autumn is the safe one. Slugs on the seedlings. Placed beside beans or tomatoes it stunts them, and that is not folklore."),
        Crop("dill", "Dill", "Anethum graveolens", .umbel, "Apiaceae",
             indoors: nil, out: nil, direct: (-2)...0, days: 40...60, per: 4, inches: 6,
             hardy: .halfHardy, again: 21, window: 30, fall: 8...10,
             with: ["cabbage", "cucumber", "onion"], against: ["carrot", "tomato"],
             form: .herb, tint: 42,
             note: "A feathery annual sown direct where it will grow, because its taproot hates being moved. Sown from two weeks before the last frost, and again every three weeks for a steady supply of leaf; the plant flowers at two months and the leaf is finished when it does. The flowering umbels draw hoverflies and lacewings that clear aphids from the rest of the plot, which is the real reason to keep it.",
             trouble: "It bolts fast in heat and there is no leaf once the flower stalk rises; sow small and often. Placed beside carrots it crosses with them and the carrots taste of nothing. Aphids on the tips in a dry June. Otherwise it self-seeds and looks after itself."),
        Crop("basil", "Basil", "Ocimum basilicum", .mint, "Lamiaceae",
             indoors: 6...8, out: 2...3, direct: 2...3, days: 60...75, per: 4, inches: 6,
             hardy: .veryTender, again: nil, window: 60, fall: nil,
             with: ["tomato", "pepper", "okra"], against: ["sage", "rosemary"],
             form: .herb, tint: 43,
             note: "The tenderest herb in the plot. Basil blackens at forty degrees, so it is started under lights six to eight weeks before the last frost and not set out until two or three weeks after it, beside the tomatoes it was born to go with. Four to a square. Pinch the growing tip every week from six inches and the plant bushes out instead of flowering; a plant allowed to flower stops making leaf.",
             trouble: "A cold night, even without frost, blackens the leaves. Downy mildew yellows them from below in a humid summer. Slugs take the seedlings. Fusarium wilt is seed-borne; buy from a clean source. Left unpinched it flowers in July and the leaves turn bitter."),
        Crop("parsley", "Parsley", "Petroselinum crispum", .umbel, "Apiaceae",
             indoors: 8...10, out: (-2)...0, direct: (-3)...(-1), days: 70...90, per: 4, inches: 6,
             hardy: .halfHardy, again: nil, window: 90, fall: nil,
             with: ["tomato", "carrot", "asparagus"], against: ["lettuce", "mint"],
             form: .herb, tint: 44,
             note: "Parsley seed takes three to four weeks to germinate, which is why the old gardeners said it went to the devil and back before it came up. Soak it overnight, sow it eight to ten weeks before the last frost under cover or direct a few weeks before it, and be patient. Once up it gives for a full year: cut the outer stalks and the centre keeps coming. It is a biennial and flowers in its second spring.",
             trouble: "Slow, uneven germination is the main complaint; old seed makes it worse. Carrot fly attacks the root as it does the whole family. Crown rot in a waterlogged winter. The second-year plant bolts and is bitter; sow fresh each year."),
        Crop("cilantro", "Cilantro", "Coriandrum sativum", .umbel, "Apiaceae",
             indoors: nil, out: nil, direct: (-2)...0, days: 45...55, per: 9, inches: 4,
             hardy: .halfHardy, again: 14, window: 14, fall: 6...8,
             with: ["spinach", "tomato", "pepper"], against: ["fennel", "carrot"],
             form: .herb, tint: 45,
             note: "Coriander is grown for leaf in the cool months and for seed in the warm ones, and it decides which for itself. Sown direct from two weeks before the last frost, nine to a square, it gives leaf for three or four weeks and then bolts; so it is sown every fortnight, and again in late summer for the best crop of all, which stands into the frosts. Let one sowing flower and dry for the seed.",
             trouble: "It bolts at the first warmth and there is nothing to be done except sow again; summer cilantro is a seed crop, not a leaf crop. Transplanting it makes it bolt at once, so it is never started indoors. Aphids on the flower stalks. Otherwise trouble-free."),
        Crop("chives", "Chives", "Allium schoenoprasum", .allium, "Amaryllidaceae",
             indoors: 6...8, out: (-2)...0, direct: (-2)...0, days: 60...80, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 120, fall: nil,
             with: ["carrot", "tomato", "strawberry"], against: ["pea", "bushbean"],
             form: .stalk, tint: 46,
             note: "A perennial allium that holds a square for years. Started from seed under cover or sown direct around the last frost, it makes a grassy clump that is cut to an inch above the ground whenever it is wanted and grows straight back. The purple pompom flowers in May are edible and the bees love them. Lift and divide the clump every third spring, and it will outlive the gardener.",
             trouble: "Almost nothing. Rust orange-spots the leaves in a wet summer; cut the clump to the ground and the new growth is clean. An old, crowded clump goes thin in the middle and needs dividing. Placed among peas and beans it slows them, as every allium does."),
        Crop("thyme", "Thyme", "Thymus vulgaris", .mint, "Lamiaceae",
             indoors: 6...8, out: 0...2, direct: nil, days: 80...90, per: 4, inches: 6,
             hardy: .hardy, again: nil, window: 120, fall: nil,
             with: ["cabbage", "strawberry", "eggplant"], against: ["basil", "mint"],
             form: .herb, tint: 47,
             note: "A low woody perennial from the dry hills of the Mediterranean, which is the whole of its cultivation: poor soil, full sun, and no coddling. It is started under cover six to eight weeks before the last frost, since the seed is dust and slow, and set out around it, four to a square at the sunny end of a bed. Cut it back by a third after flowering and it stays compact for five or six years.",
             trouble: "Wet feet kill it: in heavy soil or a wet winter the roots rot and the plant browns from the centre. It goes woody and bare at the base if it is never cut. Beside basil or mint it is out-competed for water and light. Otherwise pests leave it alone."),
        Crop("oregano", "Oregano", "Origanum vulgare", .mint, "Lamiaceae",
             indoors: 6...8, out: 0...2, direct: nil, days: 80...90, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 120, fall: nil,
             with: ["pepper", "cabbage", "cucumber"], against: ["basil", "mint"],
             form: .herb, tint: 48,
             note: "A sprawling perennial that wants the same as thyme: lean soil and sun. Started under cover and set out around the last frost, one to a square because it spreads, it is cut hard just as the flowers open, when the oil is strongest, and dried in bunches. The flowering stems pull in bees and hoverflies. Greek oregano has the flavour; the common kind is mostly leaf and no bite.",
             trouble: "Rots in wet ground. Grown in rich soil it makes a great deal of soft leaf with no flavour. Spider mites in a hot dry spell indoors. It self-seeds into paths and neighbouring squares and must be pulled back every spring."),
        Crop("sage", "Sage", "Salvia officinalis", .mint, "Lamiaceae",
             indoors: 6...8, out: 0...2, direct: nil, days: 75...90, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 120, fall: nil,
             with: ["cabbage", "carrot", "rosemary"], against: ["cucumber", "basil"],
             form: .herb, tint: 49,
             note: "A grey-leaved shrub that takes a whole square and keeps it for four or five years. Started under cover six to eight weeks before the last frost and set out around it in the driest, sunniest ground in the plot. The leaves are picked sparingly in the first year and freely after, and the plant is pruned hard in spring to stop it going leggy. It is said to keep cabbage whites off the brassicas beside it.",
             trouble: "Wet winters and heavy soil rot the roots. An unpruned bush splits open at the centre and has to be replaced. Powdery mildew in a humid summer. Beside cucumbers it is said to stunt them, and it certainly wants a drier bed than they do.")
    ]
}

enum CropsF {
    static let list: [Crop] = [
        Crop("rosemary", "Rosemary", "Salvia rosmarinus", .mint, "Lamiaceae",
             indoors: 8...10, out: 1...3, direct: nil, days: 90...120, per: 1, inches: 12,
             hardy: .halfHardy, again: nil, window: 150, fall: nil,
             with: ["sage", "cabbage", "bushbean"], against: ["basil", "mint"],
             form: .herb, tint: 50,
             note: "An evergreen shrub of the dry coast that lives for years in a mild zone and is lifted into a pot for winter in a cold one. From seed it is slow and uncertain, sown under cover ten weeks before the last frost; from a cutting it is quick. It is set out a week or two after the frost into sharp-drained soil against a warm wall and watered only until it is established. Cut sprigs as wanted all year.",
             trouble: "Cold wet roots in winter kill it faster than frost does; drainage is everything. A hard freeze below fifteen degrees kills the top growth. Overwatered indoors it drops its needles. Powdery mildew in still humid air. Otherwise it wants to be left alone."),
        Crop("mint", "Mint", "Mentha spicata", .mint, "Lamiaceae",
             indoors: 6...8, out: (-1)...1, direct: nil, days: 60...90, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 150, fall: nil,
             with: ["cabbage", "tomato", "pea"], against: ["parsley", "basil"],
             form: .herb, tint: 51,
             note: "Mint spreads by underground runner and will take a bed in two seasons, so it is grown in a pot sunk into its square with the rim above the soil. Started under cover or from a rooted piece, set out around the last frost, and cut to the ground twice a summer for the freshest leaf. It is the one herb that wants water and part shade. Its scent is said to confuse the cabbage white and the carrot fly.",
             trouble: "Escaping the pot is the whole problem; check for runners over the rim every month. Rust, orange pustules under the leaf, is common; cut to the ground and burn the cuttings. Left uncut it goes leggy and the leaves go small and harsh."),
        Crop("strawberry", "Strawberry", "Fragaria ananassa", .sundry, "Rosaceae",
             indoors: nil, out: (-3)...(-1), direct: nil, days: 60...90, per: 4, inches: 6,
             hardy: .hardy, again: nil, window: 30, fall: nil,
             with: ["spinach", "lettuce", "thyme"], against: ["cabbage", "broccoli"],
             form: .runner, tint: 52,
             note: "Bare-root crowns are planted a few weeks before the last frost with the crown exactly at soil level, four to a square. June-bearing kinds crop once in early summer and are best in their second year; everbearing kinds give from about ten weeks after planting until frost. Straw under the fruit keeps it clean and dry. Runners are cut off unless new plants are wanted; a bed is renewed every three years.",
             trouble: "Grey mould rots the fruit in a wet June; pick daily and keep straw under it. Birds take every ripe berry unless netted. Slugs hollow the fruit from below. Planted too deep the crown rots; too shallow it dries. Beside brassicas both do worse."),
        Crop("rhubarb", "Rhubarb", "Rheum hybridum", .sundry, "Polygonaceae",
             indoors: nil, out: (-4)...(-2), direct: nil, days: 365...400, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 60, fall: nil,
             with: ["garlic", "onion", "strawberry"], against: ["melon", "cucumber"],
             form: .leafy, tint: 53,
             note: "A perennial that holds its ground for twenty years, planted as a crown a month before the last frost into the richest soil in the plot with the bud just showing. Nothing is picked the first year; the second year a few stalks; from the third year, stalks are pulled, never cut, from April to June and then the plant is left to rebuild. The leaves are poisonous and go on the compost, not the table.",
             trouble: "Pulling in the first year weakens the crown for good. Crown rot in wet ground. A flower stalk in spring is cut out at once. A tired old crown makes thin stalks and is lifted and split in winter. Slugs in the crown."),
        Crop("asparagus", "Asparagus", "Asparagus officinalis", .sundry, "Asparagaceae",
             indoors: nil, out: (-4)...(-2), direct: nil, days: 700...730, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 42, fall: nil,
             with: ["tomato", "parsley", "basil"], against: ["onion", "garlic"],
             form: .fern, tint: 54,
             note: "The longest investment in the plot: crowns planted a month before the last frost in a trench eight inches deep, and nothing cut for two years while the root builds. From the third spring the spears are cut for six weeks and then let grow into a five-foot fern that feeds the crown for next year. The bed lasts twenty years and the plan treats its squares as permanent.",
             trouble: "Cutting in the first two years starves the crown. Asparagus beetle strips the fern in summer; pick them off. Crown rot in ground that lies wet. Weeds in an established bed are pulled by hand, never hoed, because the crowns lie shallow."),
        Crop("sunflower", "Sunflower", "Helianthus annuus", .aster, "Asteraceae",
             indoors: nil, out: nil, direct: 1...3, days: 70...100, per: 1, inches: 12,
             hardy: .tender, again: nil, window: 14, fall: nil,
             with: ["cucumber", "corn", "melon"], against: ["potato", "polebean"],
             form: .flower, tint: 55,
             note: "Sown direct a week or two after the last frost, one to a square on the north side of the plot so it shades nothing, and it is ten feet tall by August. It draws bees to everything around it and the finches to its seed in September. The head is cut when the back turns yellow and the florets fall, and hung to dry. The stalks are cut and left as winter cover for beneficial insects.",
             trouble: "Sunflower roots leach a chemical that checks potatoes and pole beans nearby; keep a square between. Birds and squirrels strip the seed a day before it is ready; bag the head. A tall stalk lodges in a storm; stake it. Slugs on the seedlings."),
        Crop("nasturtium", "Nasturtium", "Tropaeolum majus", .sundry, "Tropaeolaceae",
             indoors: 2...4, out: 1...2, direct: 1...2, days: 55...65, per: 1, inches: 12,
             hardy: .tender, again: nil, window: 60, fall: nil,
             with: ["cucumber", "wintersquash", "cabbage"], against: ["fennel", "mint"],
             form: .runner, tint: 56,
             note: "The plot's trap crop: aphids and cabbage whites prefer it to almost anything, so it is sown at the edge of the brassicas and the cucurbits to take the hit. Sown direct a week after the last frost, one to a square, in poor soil, which makes it flower rather than leaf. The flowers, leaves and green seed pods are all peppery and eaten. It trails a yard and is happiest spilling off a bed edge.",
             trouble: "Rich soil gives leaves and no flowers. Blackfly colonises it, which is the point, but a plant that is being killed by them is pulled and binned. A single frost finishes it. Cabbage white caterpillars on it are picked off before they move on."),
        Crop("marigold", "French Marigold", "Tagetes patula", .aster, "Asteraceae",
             indoors: 6...8, out: 1...2, direct: 1...2, days: 50...60, per: 4, inches: 6,
             hardy: .tender, again: nil, window: 90, fall: nil,
             with: ["tomato", "pepper", "cabbage"], against: ["bushbean", "fennel"],
             form: .flower, tint: 57,
             note: "The French marigold, planted among the tomatoes since anyone can remember, and one of the few companion claims with a study behind it: its roots give off a compound that suppresses root-knot nematodes. Started under cover six to eight weeks before the last frost or sown direct after it, four to a square. Deadhead and it flowers until frost; the scent is said to confuse whitefly.",
             trouble: "Slugs and snails eat the seedlings to the ground in a wet May. Grey mould rots the flower heads in a wet summer. Spider mites in drought. A frost ends it. The nematode effect needs a whole season in the ground; a few plants in a corner do nothing."),
        Crop("calendula", "Calendula", "Calendula officinalis", .aster, "Asteraceae",
             indoors: 6...8, out: (-1)...1, direct: (-2)...0, days: 50...60, per: 4, inches: 6,
             hardy: .halfHardy, again: nil, window: 90, fall: 8...10,
             with: ["tomato", "carrot", "asparagus"], against: ["fennel", "dill"],
             form: .flower, tint: 58,
             note: "The pot marigold, hardy enough to sow direct two weeks before the last frost and to flower through the first frosts of autumn. Four to a square at the ends of beds, where its open orange flowers feed hoverflies, whose larvae eat aphids, and its sticky stems trap the aphids themselves. The petals go in salads and the flowers dry for a salve. It self-seeds and is welcome wherever it comes up.",
             trouble: "Powdery mildew whitens the leaves in late summer; cut back and it regrows clean. Aphids gather on the buds, which is part of its job. Left undeadheaded it stops flowering by August. In rich soil it flops."),
        Crop("brussels", "Brussels Sprouts", "Brassica oleracea", .brassica, "Brassicaceae",
             indoors: 6...8, out: (-2)...0, direct: nil, days: 90...110, per: 1, inches: 12,
             hardy: .hardy, again: nil, window: 45, fall: 16...18,
             with: ["onion", "beet", "potato"], against: ["tomato", "strawberry"],
             form: .tall, tint: 59,
             note: "The longest-season brassica, started under cover six to eight weeks before the last frost and set out around it, or better, timed sixteen to eighteen weeks ahead of the first fall frost so the sprouts form in cold weather. One plant to a square, firmed in hard and staked; it is top-heavy by October. The sprouts are picked from the bottom up after the first frosts, which is when they turn sweet.",
             trouble: "Loose, blown sprouts come from loose soil, drought, or too much nitrogen; firm the plant in and tread the ground. Cabbage whites, aphids in the sprouts, and cabbage root fly as for the family. A plant that rocks in the wind makes no sprouts at all; stake it in September.")
    ]
}
