import Foundation

enum TroublesA {
    static let list: [Trouble] = [
        Trouble("clubroot", "Clubroot", .disease,
                crops: ["cabbage", "broccoli", "cauliflower", "kale", "brussels", "kohlrabi", "turnip", "rutabaga", "radish", "bokchoy", "arugula", "mizuna"],
                months: (6, 10),
                signs: "The plants wilt on a warm afternoon and stand up again by morning, then wilt earlier each day. The outer leaves turn a dull purplish green. Pull one and the root is not a root at all but a swollen, distorted club, sometimes a single fist, sometimes a bunch of knuckles, that smells sour when it is broken.",
                remedy: .pull, action: "Lift every affected plant with as much root as will come, and bin or burn it; never compost it and never leave the clubs in the ground. Wash the tools and boots. The bed comes off the brassica rotation for as long as the plan allows, seven years if it can be managed.",
                prevention: "Rotate brassicas on the longest cycle the plot allows. Lime the bed the autumn before to bring the soil to pH 7.2, since the spores are far less active in sweet soil. Raise transplants in clean compost, buy sets only from a source you trust, and improve drainage.",
                symptom: .wilt),
        Trouble("carrotfly", "Carrot fly", .pest,
                crops: ["carrot", "parsnip", "celery", "parsley", "fennel", "dill"],
                months: (5, 9),
                signs: "The foliage takes on a reddish, bronzed look and the outer leaves wilt. The roots, when pulled, are scored with rusty brown tunnels just under the skin, and the creamy maggots, a quarter of an inch long, are sometimes still inside. The damage is worst on the lower half of the root.",
                remedy: .net, action: "Cover the row with a fine mesh, sealed at the soil, and keep it on; the fly is a weak flier that hunts low and finds the crop by the smell of bruised leaves. Lift what is already damaged early, before the second generation in August, and use the sound parts.",
                prevention: "Sow thinly so there is nothing to thin, and thin in the evening if it must be done, watering afterwards to settle the smell. A sowing after the first week of June misses the first generation. A mesh barrier two feet high around the bed is enough, since the fly stays low.",
                symptom: .tunnel),
        Trouble("cabbagewhite", "Cabbage white", .pest,
                crops: ["cabbage", "broccoli", "cauliflower", "kale", "brussels", "kohlrabi", "bokchoy", "arugula", "mizuna", "turnip", "nasturtium"],
                months: (5, 9),
                signs: "Ragged holes in the leaves, growing by the day, with dark green pellets of droppings in the leaf axils. Under the leaves are clusters of yellow, ribbed eggs, and on them the velvety green or the speckled yellow-and-black caterpillars. The white butterflies are seen dancing over the bed a week before.",
                remedy: .pickOff, action: "Turn every leaf and pick off the caterpillars and squash the egg clusters. Do it daily for a fortnight; the second brood is bigger than the first. A badly stripped plant will usually grow away again from the centre if the heart is untouched.",
                prevention: "Net the bed with a fine mesh from the day the transplants go in, held clear of the leaves so the butterfly cannot lay through it. Nasturtiums at the end of the bed draw the eggs away from the cabbages. Check under the leaves every time you water.",
                symptom: .holes, count: 6),
        Trouble("aphids", "Aphids", .pest,
                crops: ["fava", "bushbean", "polebean", "pea", "lettuce", "kale", "cabbage", "pepper", "eggplant", "tomato", "cucumber", "nasturtium", "brussels", "calendula", "potato", "okra"],
                months: (5, 9),
                signs: "The growing tips curl and pucker and the newest leaves are sticky with honeydew, sometimes with a black sooty mould growing on it. Look closely and the shoots are furred with green, black or grey insects, wingless and slow, with ants running up and down the stem to farm them.",
                remedy: .pickOff, action: "Run a finger and thumb up each infested shoot and squash them, or knock them off with a hard jet of water in the morning so the leaves dry. On broad beans, pinch out the tops the moment the black colonies appear. Do not reach for a spray; the ladybirds arrive a week after the aphids.",
                prevention: "Go easy on nitrogen; soft, overfed growth is what the aphid wants. Sow calendula, marigold and dill along the bed for the hoverflies and lacewings whose larvae eat aphids by the hundred. Nasturtiums nearby draw the black bean aphid off the beans.",
                symptom: .curl, count: 7),
        Trouble("slugs", "Slugs and snails", .pest,
                crops: ["lettuce", "spinach", "bushbean", "polebean", "cabbage", "bokchoy", "basil", "strawberry", "zucchini", "cucumber", "endive", "chard", "pea", "sunflower", "rhubarb", "marigold"],
                months: (4, 10),
                signs: "Seedlings gone in the night, cut off at the soil or eaten to a stump, and silver trails of dried slime across the soil and the leaves in the morning. Older leaves are eaten from the edge in ragged bites and holes appear in the middle of leaves with no caterpillar to be found.",
                remedy: .pickOff, action: "Go out an hour after dark with a torch and pick them off the plants and the soil, especially after rain. Lay a board or an upturned pot beside the row and turn it every morning for the ones sheltering under it. Keep at it nightly for a week.",
                prevention: "Water in the morning so the surface is dry by night. Clear the hiding places: boards, weeds, long grass at the bed edge. A copper strip on a raised bed, sharp grit around seedlings and a pond for the frogs all help; ground beetles and thrushes do the rest.",
                symptom: .holes, count: 6),
        Trouble("blossomend", "Blossom-end rot", .disorder,
                crops: ["tomato", "pepper", "zucchini", "eggplant", "watermelon", "wintersquash"],
                months: (7, 9),
                signs: "A water-soaked spot appears on the bottom of the fruit, the end away from the stem, and grows into a sunken, leathery black patch the size of a coin or larger. The rest of the fruit ripens normally around it. It shows on the first fruits of the season more than the later ones.",
                remedy: .waterBase, action: "Water deeply and evenly at the root, every day in a heatwave, and then mulch to keep it there. Pick off the affected fruit so the plant puts its calcium into the next truss. It is not a disease and there is nothing to spray; the calcium is in the soil and could not travel.",
                prevention: "Even watering from the first flower onwards is the whole answer. Mulch the bed as soon as the soil is warm, and never let a container dry out and then flood it. Do not overfeed with nitrogen, which grows leaves faster than the roots can supply them.",
                symptom: .rot),
        Trouble("blight", "Late blight", .disease,
                crops: ["tomato", "potato", "tomatillo", "eggplant", "pepper"],
                months: (7, 9),
                signs: "Brown blotches with a pale, water-soaked edge on the leaves, spreading fast in warm wet weather, with a faint white mould under the leaf in the morning. The stems blacken in streaks, the fruit develops firm brown patches that rot, and a whole plant can collapse in three or four days.",
                remedy: .pull, action: "Cut off the first blotched leaves at once and bin them. If the stems are marked, pull the whole plant and bin it, and pick the sound green tomatoes to ripen indoors. Cut potato haulms to the ground and leave the tubers two weeks before lifting so the spores on the surface die.",
                prevention: "Space the plants for air, water at the base and never over the leaves, and grow early or resistant varieties where blight is a yearly visitor. Never compost blighted material, never leave volunteer potatoes in the ground, and rotate the nightshades every year.",
                symptom: .spots),
        Trouble("powdery", "Powdery mildew", .disease,
                crops: ["zucchini", "cucumber", "pumpkin", "wintersquash", "melon", "pea", "sage", "strawberry", "rosemary", "oregano", "thyme"],
                months: (7, 9),
                signs: "White, floury patches on the upper side of the older leaves, spreading until the leaf is coated as if with talc and then yellowing and dying. It comes in dry weather with cool, dewy nights, when the plant is stressed for water, and it starts on the squash first.",
                remedy: .waterBase, action: "Pick off the worst leaves and bin them, then water the plant deeply at the base in the morning; a plant that is not thirsty resists it. A spray of one part milk to nine of water on the remaining leaves, weekly, slows it enough to finish the crop.",
                prevention: "Space the cucurbits generously and keep them watered through August. Sow a second batch of zucchini in early July so there is a young plant when the first succumbs. Resistant varieties exist for cucumber and squash and are worth the seed.",
                symptom: .powder)
    ]
}

enum TroublesB {
    static let list: [Trouble] = [
        Trouble("bolting", "Bolting", .disorder,
                crops: ["lettuce", "spinach", "cilantro", "arugula", "bokchoy", "mizuna", "radish", "endive", "beet", "dill", "onion"],
                months: (6, 8),
                signs: "The plant, which has been a rosette of leaves, throws up a tall central stalk and sets flower. Lettuce turns bitter and milky, spinach and cilantro stop making leaves, radishes go woody. It follows a spell of heat, long days, a dry week, or a cold check in the seedling stage.",
                remedy: .pull, action: "Pull the bolted plants, since they will not return to leaf; the flowers can stay a day or two for the hoverflies if there is room. Sow again straight away in the shadiest part of the bed, and water the drill before sowing so the seed starts cool.",
                prevention: "Sow little and often, every two weeks, so a fresh row is coming up as the old one goes. Choose bolt-resistant varieties for summer, give lettuce and spinach afternoon shade, keep the water even, and sow spinach and cilantro in spring and autumn rather than through July.",
                symptom: .stalk),
        Trouble("dampingoff", "Damping off", .disease,
                crops: ["tomato", "pepper", "lettuce", "cabbage", "broccoli", "basil", "eggplant", "onion", "leek", "celery", "kale", "cauliflower"],
                months: (2, 5),
                signs: "Seedlings in the tray keel over at the soil line, the stem pinched and brown where it meets the compost, and a whole patch goes in a day or two. There may be a fine white web on the compost surface. It strikes thick sowings kept too wet and too warm in still air.",
                remedy: .waterBase, action: "Stop watering from above at once; stand the tray in an inch of water for ten minutes and let it drain. Thin the survivors so air moves between them, move them to more light and cooler air, and dust the surface with sharp sand. Prick out the sound ones into fresh compost.",
                prevention: "Sow thinly in clean trays with fresh compost, never garden soil. Water from below and only when the surface is dry. Give them a fan or an open window for moving air, full light, and a cooler room once they are up; the warmth was for germination, not for growing.",
                symptom: .wilt),
        Trouble("fleabeetle", "Flea beetle", .pest,
                crops: ["arugula", "radish", "mizuna", "bokchoy", "turnip", "eggplant", "kale", "cabbage", "rutabaga", "potato"],
                months: (4, 7),
                signs: "The leaves are peppered with tiny round holes, as if hit by shot, and the seedlings are checked and grey-looking. Brush the plants and small black or striped beetles spring away like fleas. Arugula and radish suffer most; a bad attack in a dry April can finish a sowing.",
                remedy: .net, action: "Cover the row with fleece or fine mesh straight away, sealed at the edges, and water underneath it; the beetles hate damp and the plants grow through the damage once they have six leaves. A yellow sticky card on a stick above the row catches the jumpers.",
                prevention: "Sow early in March, or after mid-June, to miss the spring peak. Keep the seedlings moist and growing fast; a checked plant is the one that gets eaten. Cover from the day of sowing, clear the weeds of the cabbage family that harbour them, and rotate the brassicas.",
                symptom: .holes),
        Trouble("cutworm", "Cutworm", .pest,
                crops: ["tomato", "pepper", "cabbage", "lettuce", "corn", "broccoli", "cauliflower", "bushbean", "kale", "brussels"],
                months: (5, 6),
                signs: "A transplant that was fine at dusk is lying on the soil at dawn, cut clean through the stem at ground level, the top untouched. Scratch in the soil an inch around the stump and there is a fat, greasy, grey-brown caterpillar curled into a C, which is the culprit.",
                remedy: .pickOff, action: "Dig with a finger around each cut plant and the neighbours in the row, find the grubs and pick them out. Fit a collar of card or a cut-down cup around the surviving transplants, pushed an inch into the soil. Replace what was lost; the grubs are few and easily found.",
                prevention: "Cultivate the bed a fortnight before planting to expose the grubs to the birds, and keep it weed-free, since the moth lays on weeds and grass. Collars at planting stop them entirely. Do not lay mulch until the transplants are established and the stems have hardened.",
                symptom: .wilt, count: 4),
        Trouble("hornworm", "Tomato hornworm", .pest,
                crops: ["tomato", "pepper", "eggplant", "tomatillo", "potato"],
                months: (7, 9),
                signs: "Whole leaves vanish from the top of the plant overnight, leaving bare stems, and there are large black droppings on the leaves below. The caterpillar is enormous, three or four inches, green with white chevrons and a horn at the tail, and so well matched to the stem that it takes a minute to find.",
                remedy: .pickOff, action: "Follow the droppings upward, find the caterpillar and pick it off; it is harmless to handle. Leave any that carry a row of white rice-grain cocoons on their back, since those are the pupae of a parasitic wasp and the hornworm is already finished and will breed more wasps.",
                prevention: "Check the plants every evening in July and August; a torch after dark shows them up. Turn the soil in autumn to expose the pupae. Dill, basil and marigold near the tomatoes bring in the parasitic wasps that keep the hornworm rare in a mixed plot.",
                symptom: .stripped, count: 3),
        Trouble("vineborer", "Squash vine borer", .pest,
                crops: ["zucchini", "pumpkin", "wintersquash", "cucumber", "melon"],
                months: (6, 8),
                signs: "A vine that was thriving wilts suddenly in the heat and does not recover by morning. At the base of the stem is a small hole with a heap of moist, sawdust-like frass beside it. Slit the stem lengthwise and the fat white grub with a brown head is inside, eating the pith.",
                remedy: .pickOff, action: "Slit the stem carefully with a knife along its length from the hole, find the grub and pick it out, then bury the slit stem under moist soil so it roots again along the buried part. Sow a replacement in early July, which is after the moth has finished laying.",
                prevention: "Cover the young plants with fleece until they flower and need the bees. Wrap the lowest six inches of stem in foil at planting. Bury the vine at two or three nodes along its length so a plant has several root systems and can spare one. Clear and bin the vines at the end of the season.",
                symptom: .wilt, count: 3),
        Trouble("leafminer", "Leaf miner", .pest,
                crops: ["chard", "beet", "spinach", "lettuce", "pea", "tomato"],
                months: (5, 9),
                signs: "Pale, winding tunnels or blistered blotches inside the leaf, between the upper and lower skins, with a little dark trail of droppings inside each. Hold the leaf to the light and the maggot shows as a small shadow at the end of the tunnel. The damage is cosmetic on beet and ruinous on chard grown for the leaf.",
                remedy: .pickOff, action: "Pick off every mined leaf as soon as the first blotch shows, while the maggot is still inside, and bin them; the plant grows fresh leaves quickly. Squash the small white eggs laid in rows under the leaves. Three pickings a week apart usually end it for the season.",
                prevention: "Cover the row with a fine mesh from sowing; the fly is small and cannot get through. Pull the lambsquarters and dock weeds nearby, which are its other homes. Rotate beet, chard and spinach together as one family, and sow them early or late to miss the May peak.",
                symptom: .pale, count: 5),
        Trouble("whiterot", "White rot", .disease,
                crops: ["garlic", "onion", "leek", "scallion", "chives"],
                months: (5, 8),
                signs: "The leaves yellow from the tip and the older ones die back while the neighbours are still green. Lift the plant and the base and roots are covered in a fluffy white mould with tiny black dots in it, like poppy seed, and the bulb is soft. It spreads outward from one plant to the next along the row.",
                remedy: .pull, action: "Lift the affected plants and their neighbours on either side, with the soil round the roots, and bin them; the black sclerotia keep in the soil for fifteen years or more, so not one may go on the compost. Wash the tools and boots before moving to another bed.",
                prevention: "Rotate the alliums on the longest cycle you can, and never bring soil, sets or plants from a plot that has had it. Buy clean sets and garlic from a reputable source. Grow onions from seed in modules, since sets are the usual way it arrives, and keep the beds well drained.",
                symptom: .yellow)
    ]
}

enum TroublesC {
    static let list: [Trouble] = [
        Trouble("rust", "Rust", .disease,
                crops: ["leek", "garlic", "chives", "bushbean", "polebean", "fava", "mint", "onion", "asparagus"],
                months: (7, 10),
                signs: "Bright orange or brown pustules like rust spots on the leaves, in rows along the veins on leeks and garlic and in scattered dots on beans, that leave orange dust on a finger when rubbed. The leaves yellow around the spots and die early. It flourishes in a warm damp August on crowded, well-fed plants.",
                remedy: .pickOff, action: "Strip the worst leaves and bin them; on leeks the inner blanched part is still good to eat. Water at the base, not over the leaves, and thin the row so air moves. It rarely kills a plant, so harvest what is ready and leave the rest to grow out of it in cooler weather.",
                prevention: "Give the alliums and beans room, and go easy on nitrogen, which grows the soft leaf that rust likes. Rotate the family every year and clear every leaf at the end of the season. Sow leeks a little later so their bulk is made after the August peak.",
                symptom: .spots, count: 5),
        Trouble("downy", "Downy mildew", .disease,
                crops: ["spinach", "lettuce", "onion", "cucumber", "pea", "basil", "kale", "arugula"],
                months: (9, 6),
                signs: "Yellow, angular patches on the upper side of the leaf, bounded by the veins, and on the underside a grey or purplish fur that is the fungus itself. It comes in cool, damp, still weather in spring and autumn, when the leaves stay wet all morning, and spreads through a bed in a week.",
                remedy: .waterBase, action: "Pick off the marked leaves and bin them, then change the watering: at the base, in the morning, never over the leaves. Thin the row so it dries quickly, and harvest the crop young rather than waiting. A bed that has had it should not grow the same family the next season.",
                prevention: "Space plants so they dry by mid-morning and never water in the evening. Sow resistant varieties of lettuce and spinach, which exist and are labelled. Rotate the families, clear crop debris promptly, and grow autumn spinach under a cloche with the ends open for air.",
                symptom: .yellow),
        Trouble("birds", "Birds on the seedlings", .pest,
                crops: ["pea", "bushbean", "polebean", "corn", "lettuce", "cabbage", "broccoli", "kale", "strawberry", "sunflower", "beet", "chard"],
                months: (3, 6),
                signs: "Pea and bean seedlings pulled clean out of the row and left lying, the seed eaten and the shoot discarded, or brassica seedlings stripped to the ribs with the leaf edges torn rather than bitten. Corn seed dug up along the drill. Pigeons in the morning and the jays and sparrows all day.",
                remedy: .net, action: "Net the row at once, on hoops or on twigs, with the mesh held a hand's width off the plants and pegged down at the edges. Replace the lost seedlings; a second sowing of peas catches up. The net can come off peas once they are six inches high and the brassicas once they have hardened.",
                prevention: "Net or cover at sowing, not after the first loss. Start peas, beans and brassicas in modules indoors and plant them out with a root, which the pigeon cannot pull. Twigs of prickly brush laid along a drill keep the pigeons off it. Strawberries want a net from the first white flower.",
                symptom: .pulled),
        Trouble("frostheave", "Frost heave", .disorder,
                crops: ["garlic", "onion", "leek", "strawberry", "kale", "spinach", "fava", "parsley", "chives", "rosemary", "thyme"],
                months: (11, 3),
                signs: "After a spell of hard frost and thaw, overwintering plants are standing half out of the soil, the crowns lifted and the roots showing, sometimes lying on their side. Garlic cloves are pushed to the surface. The freezing and thawing of the wet soil has jacked them up, an inch at a time.",
                remedy: .mulch, action: "Firm every lifted plant back in with the fingers on a mild day, pressing the soil down around the roots, and then mulch the row two inches deep with straw or leaf mould to keep the soil at one temperature. Replant any clove that has been thrown out, pointed end up.",
                prevention: "Mulch after the ground has frozen the first time, not before, so the mulch keeps the cold in and the soil does not thaw and refreeze. Plant garlic and sets at the proper depth, two inches to the top of the clove. Overwinter in the best-drained bed, since wet soil heaves most.",
                symptom: .lifted),
        Trouble("sunscald", "Sunscald", .disorder,
                crops: ["pepper", "tomato", "zucchini", "eggplant", "wintersquash", "melon", "cabbage"],
                months: (7, 8),
                signs: "A pale, papery, bleached patch on the side of the fruit that faces the afternoon sun, sunken and sometimes going grey with a secondary mould. It comes on fruit that was suddenly exposed, after leaves were lost to disease or pruning, or on peppers grown without enough foliage to shade them.",
                remedy: .net, action: "Rig a length of shade cloth or an old net curtain over the west side of the plants for the hottest weeks, and stop pruning tomatoes so hard. Pick the scalded fruit; the sound part is still good to eat. Water in the morning so the plants are turgid by the afternoon.",
                prevention: "Leave the leaf canopy on peppers and eggplants entirely, and prune tomatoes only to open the centre, never to strip the fruit trusses bare. Keep the plants healthy so they keep their leaves. Space them so each shades its neighbour's fruit in the afternoon.",
                symptom: .rot),
        Trouble("splitroot", "Split roots", .disorder,
                crops: ["carrot", "radish", "beet", "parsnip", "turnip", "cabbage", "rutabaga", "tomato", "kohlrabi"],
                months: (7, 9),
                signs: "Roots and heads cracked open lengthwise, sometimes healed over and corky, sometimes fresh and open to the slugs. Carrots split from the shoulder down, cabbage hearts burst from the top, tomatoes crack in rings round the stem. It follows a dry fortnight broken by a heavy rain or a hard watering.",
                remedy: .waterBase, action: "Water the row evenly and lightly rather than flooding it after a drought, and harvest what is ready now, since a split root does not keep. Mulch the bed at once to hold the moisture level steady. A cabbage about to burst can be held by twisting it a quarter turn to break some roots.",
                prevention: "Even moisture is the whole cure: mulch the root beds in June and water a little and often in dry spells rather than nothing and then a flood. Pull carrots and radishes as they come to size rather than leaving them to stand, and grow a split-resistant tomato.",
                symptom: .split),
        Trouble("nitrogen", "Nitrogen hunger", .disorder,
                crops: ["corn", "cabbage", "kale", "broccoli", "lettuce", "spinach", "chard", "leek", "zucchini", "cauliflower", "brussels", "celery"],
                months: (5, 8),
                signs: "The oldest, lowest leaves turn pale yellow from the tip and the midrib outward and then drop, while the top of the plant stays green but small and slow. On corn the yellow runs up the centre of the leaf in a V. The whole plant looks thin and starved and stops growing in mid-season.",
                remedy: .mulch, action: "Top-dress the row with an inch of well-rotted compost or manure worked lightly into the surface, and water it in; a pelleted organic feed is quicker. Mulch to keep it moist so the roots can take it up. Growth greens within a fortnight if the fault was feeding and not water.",
                prevention: "Follow the rotation: a legume before the hungry brassicas and corn. Dig in compost every autumn and never fresh woodchip or straw, which lock nitrogen up as they rot. Mulch to keep the soil life working, and feed the heavy feeders once in midsummer as a matter of course.",
                symptom: .yellow),
        Trouble("wireworm", "Wireworm", .pest,
                crops: ["potato", "carrot", "sweetpotato", "corn", "beet", "onion", "lettuce", "strawberry"],
                months: (4, 9),
                signs: "Narrow, clean holes bored into potatoes and carrots, as if with a wire, often several to a tuber and sometimes with the culprit still inside: a thin, shiny, golden-orange larva an inch long, tough and wiry. Seedlings wilt and die from a root eaten below. It is worst in a bed newly made from grass.",
                remedy: .pickOff, action: "Bury half a potato on a stick every yard along the row and lift it every few days, picking off the wireworms that have bored in. Harvest the potatoes early, as soon as the skins set, since the damage mounts through autumn. Fork the bed over after harvest for the birds.",
                prevention: "Cultivate a new bed made from turf often in its first two years, which exposes the larvae, and do not plant potatoes there until the third. Keep the beds weed-free of grass. Rotate the root crops, and grow a mustard green manure before potatoes, which the wireworm dislikes.",
                symptom: .tunnel, count: 5)
    ]
}
